config/routes.rb
Www::Application.routes.draw do

  mount LandingCat::Engine => '/landing'

  mount StatusCat::Engine => '/status_cat/demo'
  mount MeterCat::Engine => '/meter_cat/demo'
  mount SplitCat::Engine => '/split_cat/demo'
  mount ReportCat::Engine => '/report_cat/demo'

  root :to => 'root#index'

  get ':controller(/:action(/:id))'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper LandingCat::GoogleAnalyticsHelper

  before_filter :set_split_cat_cookie

  before_filter :require_reports if Rails.env.development?

  def require_reports
    Dir[Rails.root + 'app/reports/**/*.rb'].each { |path| require_dependency path }
  end

end

app/controllers/meter_cat_controller.rb
class MeterCatController < ApplicationController

  def index
  end

end

app/controllers/report_cat_controller.rb
class ReportCatController < ApplicationController

  def index
  end

end

app/controllers/root_controller.rb
class RootController < ApplicationController

  def index
    MeterCat.add( :root_index )
  end

end

app/controllers/spec_cat_controller.rb
class SpecCatController < ApplicationController

  def index
  end

end

app/controllers/split_cat_controller.rb
class SplitCatController < ApplicationController

  def index
  end

end

app/controllers/status_cat_controller.rb
class StatusCatController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/root_helper.rb
module RootHelper

  def root_project( name, github = nil, demo = nil )
    render :partial => 'root/project', :locals => { :name => name, :github => github, :demo => demo }
  end

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/"><%= image_tag 'logo.png', :id =>'logo' %></a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <% [ :meter_cat, :report_cat, :spec_cat, :split_cat, :status_cat ].each do |project| %>
          <% css = request.fullpath.include?( project.to_s ) ? 'active' : '' %>
          <% action = "/#{project}" %>
          <% name = t( :title, :scope => [ :projects, project ] ) %>
          <%= content_tag( :li, link_to( name, action ), :class => css ) %>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% css = request.fullpath == '/' ? 'active' : '' %>
      <% name = t( :home, :scope => :application ) %>
      <%= content_tag( :li, link_to( name, '/' ), :class => css ) %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : t( :title, :scope => :application ) %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : t( :title, :scope => :application ) %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>

    <main role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </main>

    <div id="footer">
      <div class="container">
        <span><%= t( :copyright_html, :scope => :application, :year => Date.today.year ) %></span>
      </div>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= google_analytics_tracking %>

  </body>
</html>

app/views/meter_cat/index.html.erb
<h1><%= t( :title, :scope => [ :projects, :meter_cat ] ) %></h1>
<p><%= t( :description, :scope => [ :projects, :meter_cat ] ) %></p>

<p>
  <%= link_to( t( :github, :scope => :application ), METER_CAT_GITHUB_URL ) %>
  |
<%= link_to( t( :demo, :scope => :application ), meter_cat_path ) %>
</p>

app/views/report_cat/index.html.erb
<h1><%= t( :title, :scope => [ :projects, :report_cat ] ) %></h1>
<p><%= t( :description, :scope => [ :projects, :report_cat ] ) %></p>

app/views/root/_project.html.erb
<div class="project col-md-6">
    <h2><%= t( :title, :scope => [ :projects, name ] ) %></h2>
    <p><%= t( :description, :scope => [ :projects, name ] ) %></p>
    <p>
      <%= link_to t( :learn_more, :scope => :application ), :controller => name  %>
      <%= raw !github ? '' : ' | ' + link_to( t( :github, :scope => :application ), github ) %>
      <%= raw !demo ? '' : '| ' + link_to( t( :demo, :scope => :application ), demo ) %>
    </p>
</div>

app/views/root/index.html.erb
<h1><%= t( :title, :scope => :application ) %></h1>
<div class="row">
    <%= root_project( :meter_cat, METER_CAT_GITHUB_URL, meter_cat_path ) %>
    <%= root_project( :report_cat, REPORT_CAT_GITHUB_URL, report_cat_path ) %>
    <%= root_project( :spec_cat, SPEC_CAT_GITHUB_URL ) %>
    <%= root_project( :split_cat, SPLIT_CAT_GITHUB_URL, split_cat_path ) %>
    <%= root_project( :status_cat, STATUS_CAT_GITHUB_URL, status_cat_path ) %>
</div>

app/views/spec_cat/index.html.erb
<h1><%= t( :title, :scope => [ :projects, :spec_cat ] ) %></h1>
<p><%= t( :description, :scope => [ :projects, :spec_cat ] ) %></p>

<p>
  <%= link_to( t( :github, :scope => :application ), SPEC_CAT_GITHUB_URL ) %>
</p>

app/views/split_cat/index.html.erb
<h1><%= t( :title, :scope => [ :projects, :split_cat ] ) %></h1>
<p><%= t( :description, :scope => [ :projects, :split_cat ] ) %></p>

app/views/status_cat/index.html.erb
<h1><%= t( :title, :scope => [ :projects, :status_cat ] ) %></h1>
<p><%= t( :description, :scope => [ :projects, :status_cat ] ) %></p>